
export const ADD_TO_CART = 'ADD_TO_CART';

export const ADD_ITEM_TO_CART = 'ADD_ITEM_TO_CART';

export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';

// nb???
export const CHANGE_ITEM_QUANTITY = 'CHANGE_ITEM_QUANTITY';

// export const SHOW_CART_ITEMS = 'SHOW_CART_ITEMS';
export const FETCH_CART_ITEMS = 'FETCH_CART_ITEMS';

export const FETCH_ITEMS_IN_STOCK = 'FETCH_ITEMS_IN_STOCK';

// export const CHECKOUT = 'CHECKOUT';

export const BUY_ITEMS = 'BUY_ITEMS';

export const ADD_NEW_ITEM_TO_STOCK = 'ADD_NEW_ITEM_TO_STOCK';

export const REQUEST_ITEMS_IN_STOCK = 'REQUEST_ITEMS_IN_STOCK';

export const UPDATE_ITEM_AMT = 'UPDATE_ITEM_AMT';